path: C:/Users/damia/PycharmProjects/object-tracker-dl/data
train: images/train
val: images/val


nc: 24
names:
  0: 'unlabeled'
  1: 'paved-area'
  2: 'dirt'
  3: 'grass'
  4: 'gravel'
  5: 'water'
  6: 'rocks'
  7: 'pool'
  8: 'vegetation'
  9: 'roof'
  10: 'wall'
  11: 'window'
  12: 'door'
  13: 'fence'
  14: 'fence-pole'
  15: 'person'
  16: 'dog'
  17: 'car'
  18: 'bicycle'
  19: 'tree'
  20: 'bald-tree'
  21: 'ar-marker'
  22: 'obstacle'
  23: 'conflicting'